name: Release Workflow
on:
  push:
    tags:
      - v*.*.*

env:
  premake: 5.0.0-beta1

jobs:
  upload_release_assets:
    name: Upload Release Assets
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create environment variables
        run: |
          $prefix = "refs/tags/v"
          $version = $env:GITHUB_REF.Substring($prefix.Length)
          echo "RED4EXT_VERSION=${version}" | Out-File -FilePath $env:GITHUB_ENV -Encoding UTF8 -Append

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Download Premake
        shell: powershell
        run: Invoke-WebRequest https://github.com/premake/premake-core/releases/download/v${{ env.premake }}/premake-${{ env.premake }}-windows.zip -OutFile ./premake/premake.zip

      - name: Extract Premake
        shell: powershell
        run: Expand-Archive -Path ./premake/premake.zip -DestinationPath ./premake

      - name: Generate projects
        run: |
          cd premake
          ./generate_projects.bat

      - name: Build
        run: |
          cd premake/projects
          MSBuild.exe RED4ext.sln -v:minimal -m -property:Configuration=Release

      - name: Prepare files
        run: |
          # Create the necessary directories.
          New-Item -ItemType directory -Path release | Out-Null
          New-Item -ItemType directory -Path release/red4ext | Out-Null
          New-Item -ItemType directory -Path release/red4ext/plugins | Out-Null
          New-Item -ItemType directory -Path release/bin/x64 | Out-Null

          # Copy build artifacts.
          Copy-Item -Path build/release/bin/RED4ext.dll -Destination release/red4ext
          Copy-Item -Path build/release/bin/powrprof.dll -Destination release/bin/x64

          # Concatenate the license and third party licenses.
          $license = Get-Content -Path LICENSE.md
          Add-Content -Path release/red4ext/LICENSE.txt -Value $license

          Add-Content -Path release/red4ext/LICENSE.txt -Value ""

          $third_party = Get-Content -Path THIRD_PARTY_LICENSES.md
          Add-Content -Path release/red4ext/LICENSE.txt -Value $third_party

          # Create a zip file.
          Compress-Archive -Path release/* -DestinationPath red4ext_${env:RED4EXT_VERSION}.zip

      - name: Prepare PDBs
        run: |
          # Create the necessary directories.
          New-Item -ItemType directory -Path release_pdbs | Out-Null
          New-Item -ItemType directory -Path release_pdbs/bin | Out-Null
          New-Item -ItemType directory -Path release_pdbs/libs | Out-Null

          # Copy the PDBs.
          Copy-Item build/release/bin/*.pdb release_pdbs/bin
          Copy-Item build/release/libs/*.pdb release_pdbs/libs

          # Create a zip file.
          Compress-Archive -Path release_pdbs/* -DestinationPath red4ext_${env:RED4EXT_VERSION}_pdbs.zip

      - name: Generate hashes
        run: |
          # Files zip.
          $hash = Get-FileHash -Algorithm SHA256 -Path red4ext_${env:RED4EXT_VERSION}.zip
          $hash | Format-List

          $only_hash = $hash | ForEach-Object { $_.Hash }
          echo "RED4EXT_SHA256=${only_hash}" | Out-File -FilePath $env:GITHUB_ENV -Encoding UTF8 -Append

          # PDBs zip.
          $hash = Get-FileHash -Algorithm SHA256 -Path red4ext_${env:RED4EXT_VERSION}_pdbs.zip
          $hash | Format-List

          $only_hash = $hash | ForEach-Object { $_.Hash }
          echo "RED4EXT_SHA256_PDBS=${only_hash}" | Out-File -FilePath $env:GITHUB_ENV -Encoding UTF8 -Append

      - name: Upload assets
        uses: softprops/action-gh-release@fe9a9bd3295828558c7a3c004f23f3bf77d155b2 # Use commit hash instead of version, this commit introduce append_body option, which is not present in the release version.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          append_body: true
          body: |       
            ### SHA256 Hashes of the release artifacts

            - red4ext_${{ env.RED4EXT_VERSION }}.zip
              - ${{ env.RED4EXT_SHA256 }}
            - red4ext_${{ env.RED4EXT_VERSION }}_pdbs.zip
              - ${{ env.RED4EXT_SHA256_PDBS }}
          files: |
            red4ext_${{ env.RED4EXT_VERSION }}.zip
            red4ext_${{ env.RED4EXT_VERSION }}_pdbs.zip
